name: Terraform Multi-Module

on:
  push:
    branches: [main]
    paths:
      - 'network/**'
      - 'bucket/**'

jobs:
  network:
    name: Terraform Network
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: network
        run: terraform init

      - name: Terraform Plan
        working-directory: network
        run: terraform plan

      - name: Terraform Apply
        working-directory: network
        run: terraform apply -auto-approve

  bucket:
    name: Terraform Bucket
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: bucket
        run: terraform init

      - name: Terraform Plan
        working-directory: bucket
        run: terraform plan

      - name: Terraform Apply
        working-directory: bucket
        run: terraform apply -auto-approve