name: Terraform Mono Repo

on:
  push:
    branches: [main]
    paths:
      - 'network/**'
      - 'bucket/**'
  pull_request:
    paths:
      - 'network/**'
      - 'bucket/**'

jobs:
  network:
    name: Terraform Network
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: network
        run: terraform init

      - name: Terraform Format
        working-directory: network
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: network
        run: terraform validate

      - name: Terraform Plan
        working-directory: network
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: network
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #AWS_DEFAULT_REGION: ap-south-1
        run: terraform apply -auto-approve

  bucket:
    name: Terraform bucket
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: bucket
        run: terraform init

      - name: Terraform Format
        working-directory: bucket
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: bucket
        run: terraform validate

      - name: Terraform Plan
        working-directory: bucket
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #AWS_DEFAULT_REGION: ap-south-1
        run: terraform apply -auto-approve
